// Singin
export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";
export const SET_INITIAL_STATE = "SET_INITIAL_STATE";

// Marker
export const ADD_MARKERS = "ADD_MARKERS";
export const UPLOAD_MARKER_STARTED = "UPLOAD_MARKER_STARTED";
export const UPLOAD_MARKER_SUCCESS = "UPLOAD_MARKER_SUCCESS";
export const UPLOAD_MARKER_FAILURE = "UPLOAD_MARKER_FAILURE";
export const DELETE_MARKER = "DELETE_MARKER";

// Trip
export const ADD_TRIPS = "ADD TRIPS";
export const UPLOAD_TRIP_STARTED = "UPLOAD_TRIP_STARTED";
export const UPLOAD_TRIP_SUCCESS = "UPLOAD_TRIP_SUCCESS";
export const UPLOAD_TRIP_FAILURE = "UPLOAD_TRIP_FAILURE";
export const CHANGE_ACTIVE_TRIP = "CHANGE_ACTIVE_TRIP";
